app_ecommerce/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import product_list,product_detail
from . import views

app_name='app_ecommerce'

urlpatterns=[
    # path('',home,name='home'),
    # path('product_list/', product_list, name='product_list'),
    #path('product_detail/',product_detail,name='product_detail'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^/search/$',views.search,name='search')

]

# from django.conf.urls import url
# from . import views

# app_name = 'app_ecommerce'

# urlpatterns = [
#     url(r'^$', views.product_list, name='product_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
# ]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('',include('app_ecommerce.urls')),
    path('ordes/',include('orders.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls')),
    path('user/',include('loginapp.urls')),
    #path('search/',include('app_ecommerce.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

from .views import user_login,signup,password_reset,activate_account,user_logout

app_name='loginapp'
SOCIAL_AUTH_URL_NAMESPACE = 'loginapp:social'

urlpatterns=[
    #path('',login,name='login'),
    url('signup/',signup,name='signup'),
    url(r'^login/$',user_login,name='login'),
    url(r'^logout/$',user_logout,name='logout'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name = "forget7.html",email_template_name = 'registrations/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "registrations/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "registrations/password_reset_complete.html"), name='password_reset_complete'),
    url(r'^activate_account/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate_account, name='activate_account'),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

orders/urls.py
from django.conf.urls import url
from . import views

app_name='orders'

urlpatterns=[
    url(r'^create/$',views.order_create,name='order_create')
]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from app_ecommerce.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% include 'user/header.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}
    
    <div class="container">
        <div class="row" style="margin-top: 6%">
                <h2>Hi {{ user.username }}  </h2>
        <h3> Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                    {% if cart|length > 0 %}
                        My Shopping Order:
                        <a href="{% url "cart:cart_detail" %}" style="color: #944646">
                            {{ totail_items }} item in  {{ cart.get_total_price }}
                        </a>
                        {% else %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </span>
        </h3>
            <table class="table table-striped table-hover" border="1">
                <thead style="background-color: #5AC8FA">
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Unit Price</th>
                        <th>Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                    {% with product=item.product  %}
                        <tr>
                            <td>
                                <a href="{{ product.get_absolute_url }}">
                                    <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                                </a>
                            </td>
                            <td>{{ product.name }}</td>
                            <td>
                                <form action="{% url "cart:cart_add" product.id %}" method="post">
                                    {% csrf_token %}
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" value="Update" class="btn btn-info">
                                </form>
                            </td>
                            <td>
                                <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                            </td>
                            <td> {{ item.price }}</td>
                            <td> {{ item.total_price }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b> {{ cart.get_total_price }}</b></td>
                </tr>
                </tbody>
            </table>
        <p class="text-right">
            <a href="{% url "app_ecommerce:product_list" %}" class="btn btn-default">Continue Shopping</a>
            {% if user.is_authenticated %}
            
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Checkout</a>
            {% else %}
            <ul>
            <li><a href="{% url "loginapp:signup" %}">signup</a></li>
            <li><a href="{% url "loginapp:login" %}">login</a></li>
            <li><a href="{% url "loginapp:logout" %}">logout</a></li>
            </ul>
            {% endif %}
        </p>
        </div>
    </div>
{% endblock %}
{% include 'user/footer.html' %}    