cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('',include('app_ecommerce.urls')),
    path('ordes/',include('orders.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls')),
    path('user/',include('loginapp.urls')),
    #path('search/',include('app_ecommerce.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

from .views import user_login,signup,password_reset,activate_account,user_logout

app_name='loginapp'
SOCIAL_AUTH_URL_NAMESPACE = 'loginapp:social'

urlpatterns=[
    #path('',login,name='login'),
    url('signup/',signup,name='signup'),
    url(r'^login/$',user_login,name='login'),
    url(r'^logout/$',user_logout,name='logout'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name = "forget7.html",email_template_name = 'registrations/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "registrations/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "registrations/password_reset_complete.html"), name='password_reset_complete'),
    url(r'^activate_account/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate_account, name='activate_account'),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

loginapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

class SignUpForm(UserCreationForm):
   email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
   class Meta:
       model = User
       fields = ('username', 'email', 'password1', 'password2')


class LoginForm(UserCreationForm):
    username = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.',required = True)
    class Meta:
        model = User
        fields = ('username','password')

    # def clean(self):

    #     username = self.cleaned_data.get("username")
    #     password = self.cleaned_data.get("password")
    #     user=authenticate(username=username,password=password)
    #     if not user:
    #         raise forms.ValidationError("This user does not exist")

class PasswordResetRequestForm(UserCreationForm):
   email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

loginapp/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse,request,HttpResponseRedirect
from .forms import SignUpForm,LoginForm
from django.contrib.auth.forms import UserCreationForm 
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.template import RequestContext
from django.shortcuts import render_to_response
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token_generator import account_activation_token
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required



# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        # username = request.POST.get('username')
        # print(username)
        # email = request.POST.get('email')
        # print(email)
        # password1 = request.POST.get('password1')
        # print(password1)
        # password2 = request.POST.get('password2')
        # print(password2)
        if form.is_valid():
            print(form.is_valid())
            user = form.save(commit=False)
            user.is_active = False
            
            user.save()
            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message)
            print("hi")
            return redirect('/account_activation_sent')
        
    else:
       form = SignUpForm()
    return render(request, 'register7.html', {'form': form})

def account_activation_sent(request):
    return render(request, 'account_activation_sent.html')


def activate_account(request, uidb64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Your account has been activate successfully')
       
    else:
        return HttpResponse('Activation link is invalid!')


def user_login(request):
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            print(user)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request,"user/index.html")
                else:
                    return HttpResponse("You're account is disabled.")
            else:
                print("invalid login details " + username + " " + password)
                return render(request,'register7.html')
        else:
            return render(request,'login7.html')


def password_reset(request):
    return render(request,"forget7.html")


@login_required
def user_logout(request):
    logout(request)
    return render(request,"login7.html")

loginapp/templates/login/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'loginapp:activate_account' uidb64=uid token=token %}
{% endautoescape %}

loginapp/templates/login/account_activation_sent.html
{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

loginapp/templates/login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iofrm</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/iofrm-style.css">
    <link rel="stylesheet" type="text/css" href="/static/css/iofrm-theme7.css">
</head>
<body>
    <div class="form-body">
        <div class="website-logo">
            <a href="index.html">
                <div class="logo">
                    <img class="logo-size" src="/static/images/logo-light.svg" alt="">
                </div>
            </a>
        </div>
        <!-- <div class="row">
            <div class="img-holder">
                <div class="bg"></div>
                <div class="info-holder">
                    <img src="/static/images/graphic3.svg" alt="">
                </div>
            </div> -->

            {% block content %}

            {% endblock %}

            

<script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script><script src="js/jquery.min.js"></script>
<script src="/static/js/popper.min.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/main.js"></script>
</body>
</html>

loginapp/templates/login/forget7.html
{% include 'header.html' %}

            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <div class="container">
                                <center>  
                                        <div style="padding-top: 200px; padding-bottom:200px;  padding-left:100px;  padding-right:100px;"> 
                                   <div class="col-12 col-md-9 col-lg-6   ">
                                        <h2>Password Reset</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <input class="form-control" type="text" name="email" placeholder="E-mail Address" required></br>
                            <div class="form-button full-width">
                                <button id="submit" type="submit" class="ibtn btn-forget">Send Reset Link</button></br>
                            </div>
                        </form>
                    </div>
                    <div class="form-sent">
                        <div class="tick-holder">
                            <div class="tick-icon"></div>
                        </div>
                        <h3>Password link sent</h3>
                        <p>Please check your inbox <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="523b3d34203f123b3d34203f26373f223e3326377c3b3d">[email&#160;protected]</a></p>
                        <div class="info-holder">
                            <span>Unsure if that email address was correct?</span> <a href="#">We can help</a>.
                            <p>To reset your password, enter the email address you use to sign in to website</p>

                        </div>
                    </div>
                    </center>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
{% include 'footer.html' %}

loginapp/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iofrm</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="css/iofrm-style.css">
</head>
<body>
    <div class="preview-body" class="container-fluid">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="web-logo">
                        <img src="images/logo-dark.svg" alt="">
                    </div>
                    <div class="web-title">
                        Forms in style.<br>
                        For all purposes and websites.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login1.html">
                        <img src="img/form1.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login2.html">
                        <img src="img/form2.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login3.html">
                        <img src="img/form3.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login4.html">
                        <img src="img/form4.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login5.html">
                        <img src="img/form5.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login6.html">
                        <img src="img/form6.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login7.html">
                        <img src="img/form7.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login8.html">
                        <img src="img/form8.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login9.html">
                        <img src="img/form9.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login10.html">
                        <img src="img/form10.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login11.html">
                        <img src="img/form11.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login12.html">
                        <img src="img/form12.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login13.html">
                        <img src="img/form13.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login14.html">
                        <img src="img/form14.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login15.html">
                        <img src="img/form15.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="profile1.html">
                        <img src="img/form15-p.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login16.html">
                        <img src="img/form16.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login17.html">
                        <img src="img/form17.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login18.html">
                        <img src="img/form18.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login19.html">
                        <img src="img/form19.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login20.html">
                        <img src="img/form20.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login21.html">
                        <img src="img/form21.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="login22.html">
                        <img src="img/form22.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="job-app1.html">
                        <img src="img/form23.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="job-app2.html">
                        <img src="img/form24.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="payment1.html">
                        <img src="img/form25.jpg" alt="">
                    </a>
                </div>
                <div class="col-12 col-sm-6 col-md-4">
                    <a class="img-link" target="_blank" href="contact1.html">
                        <img src="img/form26.jpg" alt="">
                    </a>
                </div>
            </div>
        </div>
    </div>
<script src="js/jquery.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/main.js"></script>
</body>
</html>

loginapp/templates/login/login7.html
{% include 'header.html' %}

            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        
                        <div class="container" padding: 250px 50px 75px 100px>
                            <center>
                                    <div style="padding-top: 200px; padding-bottom:200px;  padding-left:100px;  padding-right:100px;">
                        <div class="col-12  col-md-9 col-lg-6 col-xl-7" padding-top:100px;>
                          
                                {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                        <form method="POST" action=''>
                        {% csrf_token %}
                        <h2>Login</h2></br>
                        <div class="container"  margin-top=100px;>
                            <input class="form-control" type="text" name="username" placeholder="username" required><br/>
                            <input class="form-control" type="password" name="password" placeholder="Password" required><br/>
                            <div class="form-button">
                                <button id="submit" type="submit" class="ibtn" >Login</button> <a href="{% url "loginapp:password_reset" %}">Forget password?</a>
                            </div>
                        </div>
                        </form>
                    
                        <div class="other-links">
                            <span>Or login with </span><a href="#">Facebook </a><a href="{% url 'loginapp:social:begin' 'google-oauth2' %}"> Google </a><a href="#"> Linkedin </a>
                        </div>
                    </div>
                    </center>
                </div>
            </div>
      

{% include 'footer.html' %}

loginapp/templates/login/logout.html
<h3>you are logout</h3>

loginapp/templates/login/main-pages_xXxXx.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iofrm</title>
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/fontawesome-all.min.css">
    <link rel="stylesheet" type="text/css" href="css/iofrm-style.css">
    <link rel="stylesheet" type="text/css" href="css/iofrm-theme7.css">
</head>
<body>
    <div class="form-body">
        <div class="website-logo">
            <a href="index.html">
                <div class="logo">
                    <img class="logo-size" src="images/logo-light.svg" alt="">
                </div>
            </a>
        </div>
        <div class="row">
            <div class="img-holder">
                <div class="bg"></div>
                <div class="info-holder">
                    <img src="images/graphic3.svg" alt="">
                </div>
            </div>
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>Get more things done with Loggin platform.</h3>
                        <p>Access to the most powerfull tool in the entire design and web industry.</p>
                        <div class="page-links">
                            <a href="login7.html" class="active">Login</a><a href="register7.html">Register</a>
                        </div>
                        <form>
                            <input class="form-control" type="text" name="username" placeholder="E-mail Address" required="" autocomplete="off" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%;">
                            <input class="form-control" type="password" name="password" placeholder="Password" required="" autocomplete="off" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: pointer;">
                            <div class="form-button">
                                <button id="submit" type="submit" class="ibtn">Login</button> <a href="forget7.html">Forget password?</a>
                            </div>
                        </form>
                        <div class="other-links">
                            <span>Or login with</span><a href="#">Facebook</a><a href="#">Google</a><a href="#">Linkedin</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<script src="js/jquery.min.js"></script>
<script src="js/popper.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/main.js"></script>

</body></html>

loginapp/templates/login/register7.html
{% load static %}
{% include 'header.html' %}

            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                           
                 
                       
                        <div class="container">
                         <center>   
                                <div style="padding-top: 100px; padding-bottom:150px;  padding-left:100px;  padding-right:100px;">

                            <div class="col-12 col-md-9 col-lg-6   ">
                                    <h2>Register</h2><br>
                        <form method="POST" action=''>
                            {% csrf_token %}
                           
                             
                            <div class='container'> 
                            <input class="form-control" type="text" name="username" placeholder="User Name" maxlength="60" required><br/>
                       
                            <input class="form-control" type="email" name="email" placeholder="E-mail Address" required><br/>
                            <input class="form-control" type="password" name="password1" placeholder="Password" required><br/>
                            <input class="form-control" type="password" name="password2" placeholder=" Confirm Password" required><br/>

                            <div class="form-button">
                                <button id="submit" type="submit" class="ibtn">Register</button></br>
                            </div>
                        </div>
                        </form>
                        <div class="other-links">
                            <span>Or register with</span><a href="#">Facebook</a><a href="#">Google</a><a href="#">Linkedin</a>
                        
                        </div>
                </div>
                </div>
                
            </center>
            </div>
        </div>
    </div>

    {% include 'footer.html' %}