app_ecommerce/urls.py
from django.urls import path,include
from django.conf.urls import url
from .views import product_list,product_detail
from . import views

app_name='app_ecommerce'

urlpatterns=[
    # path('',home,name='home'),
    # path('product_list/', product_list, name='product_list'),
    #path('product_detail/',product_detail,name='product_detail'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
    url(r'^/search/$',views.search,name='search')

]

# from django.conf.urls import url
# from . import views

# app_name = 'app_ecommerce'

# urlpatterns = [
#     url(r'^$', views.product_list, name='product_list'),
#     url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
#     url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
# ]

cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart', include('cart.urls')),
    path('',include('app_ecommerce.urls')),
    path('ordes/',include('orders.urls')),
    path('paypal/',include('paypal.standard.ipn.urls')),
    path('payment/',include('payment.urls')),
    path('user/',include('loginapp.urls')),
    #path('search/',include('app_ecommerce.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/urls.py
from django.urls import path
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views

from .views import user_login,signup,password_reset,activate_account,user_logout

app_name='loginapp'
SOCIAL_AUTH_URL_NAMESPACE = 'loginapp:social'

urlpatterns=[
    #path('',login,name='login'),
    url('signup/',signup,name='signup'),
    url(r'^login/$',user_login,name='login'),
    url(r'^logout/$',user_logout,name='logout'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(template_name = "forget7.html",email_template_name = 'registrations/password_reset_email.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name = "registrations/password_reset_done.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name = "registrations/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name = "registrations/password_reset_complete.html"), name='password_reset_complete'),
    url(r'^activate_account/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate_account, name='activate_account'),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

orders/urls.py
from django.conf.urls import url
from . import views

app_name='orders'

urlpatterns=[
    url(r'^create/$',views.order_create,name='order_create')
]

payment/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls import url
from . import views

app_name='payment'

urlpatterns=[
    url(r'^payment/', include('paypal.standard.ipn.urls')),
    url(r'^process_payment/$', views.process_payment, name='process_payment'),
    url(r'^payment_done/$', views.payment_done, name='payment_done'),
    url('payment_cancelled/', views.payment_canceled, name='payment_cancelled'),

]

app_ecommerce/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q

#from django.utils import timezone


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True,default='')
    # created_at = models.DateTimeField(default='django.utils.timezone.now')
    # updated_at = models.DateTimeField(default='django.utils.timezone.now')

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app_ecommerce:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE,default='DEFAULT VALUE')
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True,default='')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default='DEFAULT VALUE')
    # created_at = models.DateTimeField(default='django.utils.timezone.now')
    # updated_at = models.DateTimeField(default='django.utils.timezone.now')
    image = models.ImageField(upload_to='product_photo', blank=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('app_ecommerce:product_detail', args=[self.id, self.slug])

    

orders/models.py
from django.db import models
from app_ecommerce.models import Product

# Create your models here.
class Order(models.Model):
    first_name=models.CharField(max_length=60)
    last_name=models.CharField(max_length=60)
    address=models.CharField(max_length=200)
    email=models.EmailField()
    postal_code=models.CharField(max_length=50)
    city=models.CharField(max_length=100)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=True)


    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order=models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product=models.ForeignKey(Product,related_name='order_items',on_delete=models.CASCADE)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    quantity=models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

payment/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model=Order
        fields=['first_name','last_name','address','email','postal_code','city']

app_ecommerce/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,request,HttpResponseRedirect
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.views.generic import TemplateView, ListView
from django.db.models import Q


# Create your views here.


def product_list(request, category_slug=None):
    category = None
    category = Category.objects.all()
    #print(category)
    products = Product.objects.filter(available=True)
    #print(products)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=category)


    context = {
        'category': category,
        #'categories': categories,
        'products': products
    }
    return render(request, 'index.html',{'category':category,'products':products})

def product_detail(request,id,slug):
    product = get_object_or_404(Product, id=id, slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form
    }
    return render(request, 'mycart.html', context,{'product':product})

# def search(request):
#     if request.method=='GET':
#         template_name = 'index.html'
#         print("FDS")
#         model = Product

#         def get_queryset(self):
#             query = self.request.POST.get('Product')
#             print(query)
#             if query:
#                 product = Product.objects.filter(Q(name__icontains=Product))
#                 print(product)
#             else:
#                 products = self.model.objects.none()
#                 print("aa")
#             return render(request, 'index.html',{'products':products})
#         return render(request, 'index.html',{'products':products})

def search(request): 
   
    
    model=Product
    model=Category

    if request.method =='GET':
        product = request.GET.get('Product')
        category = request.GET.get('Category')
        
        products = Product.objects.filter(Q(name__icontains=product)|Q(category__name__icontains=product))
        # categories = Category.objects.filter(name__icontains=category)
        # print(products)
        return render(request, 'index.html',{'products':products })
    return render(request, 'index.html',{'products':products })

  

orders/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
#from .tasks import order_created
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart

# Create your views here.
def order_create(request):
    cart=Cart(request)
    if request.method=='POST':
        form=OrderCreateForm(request.POST)
        if form.is_valid():
            order=form.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
            cart.clear()
            #order_created.delay(order.id)
            request.session['order.id']=order.id
            return redirect('/payment/process_payment')
        return render(request,'/payment/payment_done.html')
        #return render(request,'orders/order/created.html',{'order':order})
    else:
        form=OrderCreateForm()
    return render(request,'orders/order/create.html',{'form':form,'cart':cart})

payment/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from decimal import Decimal
from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt
from orders.models import Order


#from .models import Product, Order, LineItem
#from .forms import CartForm, CheckoutForm

# Create your views here.
@csrf_exempt
def payment_done(request):
    return render(request, 'payment/payment_done.html')
 
 
@csrf_exempt
def payment_canceled(request):
    return render(request, 'payment/payment_cancelled.html')


def process_payment(request):
    order = request.session.get('order.id')
    print(order)
    order = get_object_or_404(Order, id=order)
    host = request.get_host()
 
    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': '%.2f' % Decimal(order.get_total_cost()).quantize(Decimal('.01')),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'INR',
        'notify_url': 'http://{}{}'.format(host,reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,redirect('/payment_done')),                                           
        'cancel_return': 'http://{}{}'.format(host,redirect('/payment_cancelled')),                                              
    }
 
    form = PayPalPaymentsForm(initial=paypal_dict)
    return render(request, 'payment/process_payment.html', {'order': order, 'form': form})

app_ecommerce/templates/user/footer.html
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- start bootstrap 4.1 css -->
      <link href="/static/css/bootstrap.min.css" rel="stylesheet">
      <link rel="icon" href="/static/images/favicon.png" type="/static/images/png">
      <!-- end bootstrap 4.1 css -->
      <!-- flat-icon -->
      <link rel="stylesheet" type="text/css" href="/static/css/icons/flaticon.css">
      <!-- flat-icon -->
      <!-- slick-slider -->
      <link rel="stylesheet" href="/static/css/slick.min.css">
      <link rel="stylesheet" href="/static/css/slick-theme.min.css">
      <!-- select2 -->
      <link href="/static/css/select2.min.css" rel="stylesheet" />
      <!-- select2 -->
      <!-- slick-slider -->
      <link href="/static/css/style.css" rel="stylesheet">
      <link href="/static/css/responsive.css" rel="stylesheet">
      <title>Maan - Bootstrap E-Commerce Template</title>

   </head>

<div class="footer-area-section mt-5 pt-2">
    <div class="container">
       <div class="row mob-space-10 spaccer-50">
          <div class="col-6 col-md-6 col-sm-4 col-lg-3 col-xl-2">
             <h3>Online Shoping</h3>
             <ul class="footer-links mt-3">
                <li><a href="#">About Us</a></li>
                <li><a href="#">Core Values</a></li>
                <li><a href="#">Careers</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Sitemap</a></li>
             </ul>
          </div>
          <div class="col-6 col-md-6 col-sm-4 col-lg-3 col-xl-2">
             <h3>Policy Info</h3>
             <ul class="footer-links mt-3">
                <li><a href="#">Privacy Policy</a></li>
                <li><a href="#">Terms of Sale</a></li>
                <li><a href="#">Terms of Use</a></li>
                <li><a href="#">Report Abuse & Takedown Policy</a></li>
             </ul>
          </div>
          <div class="col-6 col-md-6 col-sm-4 col-lg-3 col-xl-2">
             <h3>NEED HELP ?</h3>
             <ul class="footer-contact">
                <li><a href="#">FAQ</a></li>
                <li><a href="#">News</a></li>
             </ul>
          </div>
          <div class="col-6 col-md-6 col-sm-4 col-lg-3 col-xl-2">
             <h3>Contact Us</h3>
             <ul class="footer-contact">
                <li><a href="#">16th Ave NY 201242</a></li>
                <li><a href="#">+61 8788 000</a></li>
                <li><a href="#">contact@onlineshoping.com</a></li>
             </ul>
          </div>
          <div class="col-12 col-md-6 col-sm-8 col-lg-4 col-xl-4 footer-logo-icon">
             <h3>Subscribe Us</h3>
             <div class="input-group">
                <input type="text" class="form-control border-right-0 srch-bar" placeholder="Enter your Email Address" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append footer-subscribe">
                   <span class="input-group-text top-srch-icon" id="basic-addon2"> <a href="#"> Subscribe</a></span>
                </div>
                <div class="spaccer-15">
                   <p>Register now to get updates on promotions and coupons. <a href="#">Or Download App</a> </p>
                </div>
             </div>
          </div>
       </div>
    </div>
 </div>
 <!-- footer-area ends here -->
 <div class="section-padding bg-white border-top pt-4 pb-4 free-delivery">
    <div class="container">
       <div class="row">
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
             <div class="feature-box">
                <i class="mdi fa fa-truck"></i>
                <h6>Free &amp; Next Day Delivery</h6>
                <p>Lorem ipsum dolor sit amet, cons...</p>
             </div>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
             <div class="feature-box">
                <i class="mdi fa fa-check-square"></i>
                <h6>100% Satisfaction Guarantee</h6>
                <p>Rorem Ipsum Dolor sit amet, cons...</p>
             </div>
          </div>
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
             <div class="feature-box">
                <i class="mdi  fa fa-handshake"></i>
                <h6>Great Daily Deals Discount</h6>
                <p>Sorem Ipsum Dolor sit amet, Cons...</p>
             </div>
          </div>
       </div>
    </div>
 </div>
 <div class="pt-4 pb-4 border-top bottom-bar">
    <div class="container">
       <div class="row no-gutters">
          <div class="col-12 col-sm-7 col-md-6 col-lg-6 text-left footer-social-links">
             <h3>Follow Us</h3>
             <ul class="follow-links">
                <li><a href="#"><i class="fab fa-facebook"></i></a>
                </li>
                <li><a href="#"><i class="fab fa-instagram"></i></a>
                </li>
                <li><a href="#"><i class="fab fa-twitter-square"></i></a>
                </li>
                <li><a href="#"><i class="fab fa-pinterest-square"></i></a>
                </li>
                <li><a href="#"><i class="fab fa-youtube"></i></a>
                </li>
                <li><a href="#"><i class="fab fa-google-plus-square"></i></a>
                </li>
             </ul>
          </div>
          <div class="col-12 col-sm-5 col-md-6 col-lg-6 payment-method-section">
             <h3>Payment</h3>
             <img class="img-fluid" alt="" src="/static/images/payment_methods.png">
          </div>
       </div>
    </div>
 </div>
 
 <!-- pop-up -->
 <script src="/static/js/jquery.min.js"></script>      
 <!-- start bootstrap 4.1 scripts -->
 <script src="/static/js/popper.min.js"></script>
 <script src="/static/js/bootstrap.min.js"></script>
 <!-- end bootstrap 4.1 scripts -->
 <!-- slick-slider -->
 <script src="/static/js/slick.min.js"></script>
 <!-- slick slider -->
 <!-- custom-js -->
 <script src="/static/js/custom.js"></script>
 <!-- custom-js -->
 <!-- font-awesome         -->
 <script src="/static/js/font-awesome.js"></script>
 <!-- font-awesome         -->
</body>
</html>
<!-- banner-area ends here -->

app_ecommerce/templates/user/header.html
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- start bootstrap 4.1 css -->
      <!-- <link href="/static/css/bootstrap.min.css" rel="stylesheet"> -->
      <link rel="icon" href="/static/images/favicon.png" type="/static/images/png">
      <!-- end bootstrap 4.1 css -->
      <!-- flat-icon -->
      <link rel="stylesheet" type="text/css" href="/static/css/icons/flaticon.css">
      <!-- flat-icon -->
      <!-- slick-slider -->
      <link rel="stylesheet" href="/static/css/slick.min.css">
      <link rel="stylesheet" href="/static/css/slick-theme.min.css">
      <!-- select2 -->
      <link href="/static/css/select2.min.css" rel="stylesheet" />
      <!-- select2 -->
      <!-- slick-slider -->
      <link href="/static/css/style.css?v=001" rel="stylesheet">
      <link href="/static/css/responsive.css" rel="stylesheet">

      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
      <title>E-Commerce </title>

   </head>
   <body class="home-page">
      <!-- start header here -->
      <!-- <div class="container-fluid top-bar">
         <div class="container">
            <div class="row">
             
               <div class="col-12 col-sm-6 col-md-6 col-lg-4 col-xl-5 shoping-site">
                  <a href="#" class="mb-0 text-white">
                  20% cashback for all users | Code: <strong><span class="text-light">OGOFARS13 <span class="mdi mdi-tag-faces"></span></span> </strong>                   </a>
               </div>
               <div class="col-12 col-sm-6 col-md-6 col-lg-8 col-xl-7 top-bar-links">
                  <ul>
                     <li><a href="#">Gifts Cards</a></li>
                     <li><a href="#">Help Center</a></li>
                     <li>
                        <a href="#"> <i class="fas fa-mobile-alt"></i> Download App</a>
                     </li>
                  </ul>
               </div>
             
            </div>
         </div>
      </div> -->
      <div class="header">
         <div class="container">
            <div class="row">
               <!-- nav -->
               <!-- logo -->
               <div class="col-12 col-sm-12 col-md-6 col-lg-2 col-xl-2 logo">
                  <a href="{% url "app_ecommerce:product_list" %}"> <img class="img-fluid" alt="" src="/static/images/logo.png"></a>
               </div>
               <!-- logo -->
               <!-- start Search bar -->
               <div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-7">
                  <!-- search-bar -->
                  <!-- <div class="input-group md-form form-sm form-2 pl-0">
                     <input class="form-control my-0 py-1 amber-border" type="text" placeholder="Search a Product, Category or Brand" aria-label="Search">
                     <div class="input-group-append">
                       
                        <a href="{{ object.get_absolute_url }}">
                        <span class="input-group-text amber lighten-3" id="basic-text1">
                        <i class="fas fa-search"></i> Search
                        </span>
                        </a>
                  
                     </div>
                  </div> -->
                  <!-- search bar -->
               </div>

               <form method='GET' action='{% url 'app_ecommerce:search' %}'>
                     
                     <input type='text' name='Product'   value=''>
                     <input class="button" type='submit' value="Search Profile">
                     </a>
                   </form>
               <!-- end Search bar -->
               <div class="col-12 col-sm-12 col-md-12 col-lg-4 col-xl-3 top-sign-in-cart-area">
                  <!-- start cart btn -->
                  <div class="dropdown cart-icon">
                     <a href="{% url "cart:cart_detail" %}" class="btn cart-btn align-top top-icons">
                     Cart <i class="flaticon-shopping-cart"></i> 
                     </a>
                  </div>
                  <!-- end cart btn -->
                  <!-- start sign-in btn -->
                  
									{% if not user.is_authenticated %}
									
                                 <div class="dropdown cart-icon">
                                       <a href="{% url "loginapp:signup" %}" class="btn cart-btn align-top top-icons">
                                          Signup <i class="flaticon-shopping-cart"></i> 
                                       </a>
                                    </div>
			

								
                                 <div class="dropdown cart-icon">
                                       <a href="{% url "loginapp:login" %}" class="btn cart-btn align-top top-icons">
                                          Login <i class="flaticon-shopping-cart"></i> 
                                       </a>
                                    </div>

										
								
									{% else %}
									
                                 <div class="dropdown cart-icon">
                                       <a href="{% url "loginapp:logout" %}" class="btn cart-btn align-top top-icons">
                                          Logout <i class="flaticon-shopping-cart"></i> 
                                       </a>
                                    </div>
										
									
									{% endif %}
									
                       
                     </div>
							

                  


                  <!-- <div class="dropdown cart-icon">
                     <a href="{% url "loginapp:login" %}" class="btn cart-btn align-top top-icons">
                        Sign In <i class="flaticon-shopping-cart"></i> 
                     </a>
                  </div>
                  <div class="dropdown cart-icon">
                        <a href="{% url "loginapp:signup" %}" class="btn cart-btn align-top top-icons">
                           Sign Up <i class="flaticon-shopping-cart"></i> 
                        </a>
                     </div> -->
                     <!-- <button type="button" class="btn dropdown-toggle align-top top-icons" data-toggle="modal" data-target="#exampleModal">
                     Sign In <i class="flaticon-user"></i>
                     </button> -->
                 
                  <!-- end sign-in btn -->
               </div>
               <!-- <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 main-navbar">
                  <nav class="navbar navbar-expand-lg">
                     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                     <i class="fa fa-bars"></i>
                     </button>
                     <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                           <li class="nav-item">
                              <a class="nav-link active" href="index.html">Home <span class="sr-only">(current)</span></a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="#">WOMEN'S</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="#">Men's</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="#">Kids</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="#">Home & Living</a>
                           </li>
                           <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Pages <i class="fas fa-chevron-down"></i>
                              </a>
                              <div class="dropdown-menu">
                                 <a class="dropdown-item" href="all-products.html">All Products</a>
                                 <a class="dropdown-item" href="order-details.html">Order Detail</a>
                                 <a class="dropdown-item" href="address.html">Address</a>
                                 <a class="dropdown-item" href="notifications.html">Notifications</a>
                                 <a class="dropdown-item" href="wallet.html">Wallet</a>
                                 <a class="dropdown-item" href="wishlist.html">Wishlist</a>
                                 <a class="dropdown-item" href="order.html">Order</a>
                                 <a class="dropdown-item" href="forgot-password.html">Forgot Password</a>
                                 <a class="dropdown-item" href="purchese-request.html">Purchese Request</a>
                                 <a class="dropdown-item" href="payment.html">Payment</a>
                                 <a class="dropdown-item" href="guest.html">Guest</a>
                              </div>
                           </li>
                           <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> My Account <i class="fas fa-chevron-down"></i>
                              </a>
                              <div class="dropdown-menu">
                                 <a class="dropdown-item" href="my-profile.html">My Profile</a>
                                 <a class="dropdown-item" href="address-detail.html">Address Detail</a>
                                 <div class="dropdown-divider"></div>
                                 <a class="dropdown-item" href="add-product.html">Add Product</a>
                                 <a class="dropdown-item" href="delivery-address.html">Delivery Address</a>
                                 <a class="dropdown-item" href="personal-information.html">Personal Information</a>
                              </div>
                           </li>
                        </ul>
                        <span class="navbar-text hidden-xs d-xs-none">
                        Worlds's Fastest <strong> Online Shopping</strong> Destination
                        </span>
                     </div>
                  </nav>
               </div> -->
            </div>
         </div>
      </div>
      


      <script src="/static/js/jquery.min.js"></script>      
      <!-- start bootstrap 4.1 scripts -->
      <script src="/static/js/popper.min.js"></script>
      <script src="/static/js/bootstrap.min.js"></script>
      <!-- end bootstrap 4.1 scripts -->
      <!-- slick-slider -->
      <script src="/static/js/slick.min.js"></script>
      <!-- slick slider -->
      <!-- custom-js -->
      <script src="/static/js/custom.js"></script>
      <!-- custom-js -->
      <!-- font-awesome         -->
      <script src="/static/js/font-awesome.js"></script>
      <!-- font-awesome         -->
   </body>
</html>